import { boolean, index, integer, jsonb, pgEnum, pgTable, serial, text, timestamp, uniqueIndex } from "drizzle-orm/pg-core";

export const runStatus = pgEnum("run_status", ["running", "success", "warning", "error", "skipped"]);
export const feedbackValue = pgEnum("feedback_value", ["interesting", "maybe", "not_suitable"]);
export const emailDigestStatus = pgEnum("email_digest_status", ["pending", "sent", "failed"]);
export const applicationStatus = pgEnum("application_status", ["want_to_apply", "applied", "interview", "rejected", "no_longer_interested"]);
export const sources = pgTable("sources", { id: serial("id").primaryKey(), slug: text("slug").notNull().unique(), name: text("name").notNull(), baseUrl: text("base_url").notNull(), enabled: boolean("enabled").notNull().default(true), createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow() });
export const sourceRuns = pgTable("source_runs", { id: serial("id").primaryKey(), sourceId: integer("source_id").notNull().references(() => sources.id), status: runStatus("status").notNull().default("running"), startedAt: timestamp("started_at", { withTimezone: true }).notNull().defaultNow(), finishedAt: timestamp("finished_at", { withTimezone: true }), resultCount: integer("result_count").notNull().default(0), newCount: integer("new_count").notNull().default(0), changedCount: integer("changed_count").notNull().default(0), warnings: jsonb("warnings").$type<string[]>().notNull().default([]), error: text("error") });
export const vacancies = pgTable("vacancies", { id: serial("id").primaryKey(), canonicalKey: text("canonical_key").notNull().unique(), title: text("title").notNull(), employer: text("employer").notNull(), location: text("location"), hoursMin: integer("hours_min"), hoursMax: integer("hours_max"), hoursOriginal: text("hours_original"), salaryMin: integer("salary_min"), salaryMax: integer("salary_max"), salaryPeriod: text("salary_period"), salaryBasisHours: integer("salary_basis_hours"), salaryOriginal: text("salary_original"), deadline: timestamp("deadline", { withTimezone: true }), description: text("description"), originalText: text("original_text").notNull(), contentHash: text("content_hash").notNull(), firstSeenAt: timestamp("first_seen_at", { withTimezone: true }).notNull().defaultNow(), lastSeenAt: timestamp("last_seen_at", { withTimezone: true }).notNull().defaultNow(), active: boolean("active").notNull().default(true), updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow() }, (t) => [index("vacancies_active_idx").on(t.active), index("vacancies_deadline_idx").on(t.deadline)]);
export const vacancyOccurrences = pgTable("vacancy_occurrences", { id: serial("id").primaryKey(), vacancyId: integer("vacancy_id").notNull().references(() => vacancies.id), sourceId: integer("source_id").notNull().references(() => sources.id), sourceRunId: integer("source_run_id").references(() => sourceRuns.id), externalId: text("external_id"), sourceUrl: text("source_url").notNull(), rawData: jsonb("raw_data").notNull(), firstSeenAt: timestamp("first_seen_at", { withTimezone: true }).notNull().defaultNow(), lastSeenAt: timestamp("last_seen_at", { withTimezone: true }).notNull().defaultNow(), active: boolean("active").notNull().default(true) }, (t) => [uniqueIndex("occurrence_source_url_idx").on(t.sourceId, t.sourceUrl), index("occurrence_external_id_idx").on(t.sourceId, t.externalId), index("occurrence_active_last_seen_idx").on(t.active, t.lastSeenAt)]);
export const preferences = pgTable("preferences", { id: serial("id").primaryKey(), hoursMin: integer("hours_min").notNull(), hoursMax: integer("hours_max").notNull(), salaryMin: integer("salary_min"), primaryCities: jsonb("primary_cities").$type<string[]>().notNull(), secondaryCities: jsonb("secondary_cities").$type<string[]>().notNull(), travelOrigin: text("travel_origin").notNull(), maxTravelMinutes: integer("max_travel_minutes").notNull(), roleFamilies: jsonb("role_families").$type<string[]>().notNull(), positiveIndicators: jsonb("positive_indicators").$type<string[]>().notNull(), negativeIndicators: jsonb("negative_indicators").$type<string[]>().notNull(), updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow() });
export const feedback = pgTable("feedback", { id: serial("id").primaryKey(), vacancyId: integer("vacancy_id").notNull().references(() => vacancies.id), value: feedbackValue("value").notNull(), aiVerdict: feedbackValue("ai_verdict"), reasonCode: text("reason_code"), note: text("note"), learningEligible: boolean("learning_eligible").notNull().default(false), createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(), updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow() }, (t) => [uniqueIndex("feedback_vacancy_idx").on(t.vacancyId)]);
export const watchedEmployers = pgTable("watched_employers", { id: serial("id").primaryKey(), name: text("name").notNull().unique(), enabled: boolean("enabled").notNull().default(true), createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow() });
export const aiAssessments = pgTable("ai_assessments", { id: serial("id").primaryKey(), vacancyId: integer("vacancy_id").notNull().references(() => vacancies.id), vacancyContentHash: text("vacancy_content_hash").notNull(), profileHash: text("profile_hash").notNull(), promptVersion: text("prompt_version").notNull(), model: text("model").notNull(), score: integer("score").notNull(), verdict: feedbackValue("verdict").notNull(), summary: text("summary").notNull(), positives: jsonb("positives").$type<string[]>().notNull(), concerns: jsonb("concerns").$type<string[]>().notNull(), assessedAt: timestamp("assessed_at", { withTimezone: true }).notNull().defaultNow(), updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow() }, (t) => [uniqueIndex("ai_assessments_vacancy_idx").on(t.vacancyId), index("ai_assessments_score_idx").on(t.score)]);
export const vacancyTracking = pgTable("vacancy_tracking", { id: serial("id").primaryKey(), vacancyId: integer("vacancy_id").notNull().references(() => vacancies.id), shortlistedAt: timestamp("shortlisted_at", { withTimezone: true }), applicationStatus: applicationStatus("application_status"), note: text("note"), createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(), updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow() }, (t) => [uniqueIndex("vacancy_tracking_vacancy_idx").on(t.vacancyId)]);
export const emailDigestRuns = pgTable("email_digest_runs", { id: serial("id").primaryKey(), runKey: text("run_key").notNull(), status: emailDigestStatus("status").notNull().default("pending"), createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(), sentAt: timestamp("sent_at", { withTimezone: true }), providerMessageId: text("provider_message_id"), error: text("error") }, (t) => [uniqueIndex("email_digest_runs_run_key_idx").on(t.runKey)]);
export const emailDigestItems = pgTable("email_digest_items", { id: serial("id").primaryKey(), runId: integer("run_id").notNull().references(() => emailDigestRuns.id), vacancyId: integer("vacancy_id").notNull().references(() => vacancies.id), createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow() }, (t) => [uniqueIndex("email_digest_items_run_vacancy_idx").on(t.runId, t.vacancyId), index("email_digest_items_vacancy_idx").on(t.vacancyId)]);
