import { desc, eq } from "drizzle-orm";
import type { Metadata } from "next";
import { getDb } from "@/lib/db";
import { sourceRuns, sources } from "@/lib/db/schema";
import { categoryLabel, parseIngestionWarning, warningCounts } from "@/lib/ingestion/shared/ingestion-warnings";
import { toggleSource } from "../actions";
import { WorkflowControl } from "@/app/components/workflow-controls";
import { formatDateTime } from "@/lib/date-format";
import { runStatusLabels } from "@/lib/run-status";
export const dynamic = "force-dynamic";
export const metadata: Metadata = { title: "Bronnen" };
export default async function Page() {
  const rows = await getDb().select({ source: sources, run: sourceRuns }).from(sources).leftJoin(sourceRuns, eq(sources.id, sourceRuns.sourceId)).orderBy(desc(sourceRuns.startedAt)); const unique = [...new Map(rows.map((row) => [row.source.id, row])).values()];
  return <><div className="page-title"><div><p className="eyebrow">Beheer · ingestie</p><h1>Bronnen</h1></div></div><div className="table-wrap"><table><caption className="sr-only">Alle ingestiebronnen met hun laatste run, resultaten en meldingen.</caption><thead><tr><th scope="col">Bron</th><th scope="col">Actief</th><th scope="col">Laatste run</th><th scope="col">Resultaten</th><th scope="col">Status / meldingen</th></tr></thead><tbody>{unique.map(({source, run}) => { const counts = warningCounts(run?.warnings ?? []); return <tr key={source.id}><th scope="row"><b>{source.name}</b><br/><a className="muted" href={source.baseUrl}>{source.baseUrl}</a></th><td><form action={toggleSource}><input type="hidden" name="id" value={source.id}/><input type="hidden" name="enabled" value={String(!source.enabled)}/><button className="secondary">{source.enabled ? "Uitschakelen" : "Inschakelen"}</button></form></td><td>{run?.finishedAt ? formatDateTime(run.finishedAt) : "Nooit"}</td><td>{run?.resultCount ?? "—"}</td><td><span className={`tag tag-${run?.status ?? "unknown"}`}>{runStatusLabels[run?.status ?? "unknown"]}</span>{run && <p className="notice-counts">{counts.critical} kritiek · {counts.warning} waarschuwing · {counts.info} info</p>}{run?.error && <p className="notice notice-critical"><b>Ingestiefout</b><br/>{run.error}</p>}{run?.warnings.map((value, index) => { const item = parseIngestionWarning(value); return <div className={`notice notice-${item.severity}`} key={index}><b>{item.severity === "critical" ? "Kritiek" : item.severity === "warning" ? "Waarschuwing" : "Info"} · {categoryLabel(item.category)}</b><br/>{item.message}{item.url && <><br/><a href={item.url}>{item.url}</a></>}</div>; })}</td></tr>; })}</tbody></table></div><section className="panel"><h2>Workflows starten</h2><p className="muted">Deze acties starten de bestaande cloud-workflows in GitHub; er draait niets lokaal of in Vercel.</p><div className="workflow-grid"><WorkflowControl action="daily"/><WorkflowControl action="reassess_preview"/><WorkflowControl action="reassess_run"/><WorkflowControl action="cleanup"/><WorkflowControl action="weekly"/></div></section></>;
}
