"use server"; import { cookies, headers } from "next/headers"; import { redirect } from "next/navigation"; import { revalidatePath } from "next/cache"; import { z } from "zod"; import { eq } from "drizzle-orm"; import { createSession } from "@/lib/auth"; import { getDb } from "@/lib/db"; import { aiAssessments, preferences, vacancyTracking, watchedEmployers } from "@/lib/db/schema"; import { calibrationResponse } from "@/lib/calibration"; import { applicationStatuses, trackingPatch, type TrackingData } from "@/lib/vacancy-tracking"; import { storeFeedback, storeFeedbackReason } from "@/lib/db/feedback"; import { feedbackDecisions, feedbackValidationMessage, isFeedbackDecision, NO_DECISION_MESSAGE, reasonCodes } from "@/lib/feedback-validation"; import { setSourceEnabled } from "@/lib/db/application-queries"; import { dispatchWorkflow, workflowActionSchema, workflowActions } from "@/lib/github-actions"; import { clearLoginAttempts, loginAllowed, passwordsMatch, recordFailedLogin } from "@/lib/login-security";
export async function login(form:FormData){ const requestHeaders=await headers();const client=requestHeaders.get("x-forwarded-for")?.split(",")[0]?.trim()||requestHeaders.get("x-real-ip")||"unknown";if(!loginAllowed(client))redirect("/login?error=1");const password=String(form.get("password")||"");if(!process.env.APP_PASSWORD||!passwordsMatch(password,process.env.APP_PASSWORD)){recordFailedLogin(client);redirect("/login?error=1");}clearLoginAttempts(client);(await cookies()).set("vacature_session",await createSession(),{httpOnly:true,secure:process.env.NODE_ENV==="production",sameSite:"lax",path:"/",maxAge:2592000}); redirect("/"); }
/** Een nieuw oordeel verandert zowel de dagelijkse funnel als de volledige lijst; beide horen te verversen. */
function refreshFunnelRoutes(vacancyId:number){revalidatePath(`/vacatures/${vacancyId}`);revalidatePath("/");revalidatePath("/vacatures");}
export type FeedbackState={status:"idle"|"success"|"error";message?:string;value?:"interesting"|"maybe"|"not_suitable"};
/** Zonder expliciet gekozen oordeel wordt er niets opgeslagen: een niet-genomen beslissing is geen oordeel en geen leersignaal. */
export async function saveFeedback(_previousState:FeedbackState,form:FormData):Promise<FeedbackState>{if(!isFeedbackDecision(form.get("value")))return{status:"error",message:NO_DECISION_MESSAGE};try{const x=z.object({vacancyId:z.coerce.number().int(),value:z.enum(feedbackDecisions),reasonCode:z.string().max(100).optional(),note:z.string().max(2000).optional()}).parse(Object.fromEntries(form));const stored=await storeFeedback(getDb(),x);refreshFunnelRoutes(x.vacancyId);return{status:"success",message:"Opgeslagen",value:stored.value};}catch(error){const message=feedbackValidationMessage(error);if(message)return{status:"error",message};console.error("Feedback opslaan mislukt",error);return{status:"error",message:"Opslaan is niet gelukt. Probeer het opnieuw."};}}
const choiceSchema=z.object({vacancyId:z.number().int(),value:z.enum(feedbackDecisions)});
export async function submitCalibrationChoice(input:z.infer<typeof choiceSchema>){if(!isFeedbackDecision(input?.value))throw new Error(NO_DECISION_MESSAGE);const x=choiceSchema.parse(input);const db=getDb();const [ai]=await db.select({verdict:aiAssessments.verdict,score:aiAssessments.score,summary:aiAssessments.summary,positives:aiAssessments.positives,concerns:aiAssessments.concerns}).from(aiAssessments).where(eq(aiAssessments.vacancyId,x.vacancyId)).limit(1);if(!ai)throw new Error("AI-beoordeling niet gevonden");const stored=await storeFeedback(db,{vacancyId:x.vacancyId,value:x.value},{requireReason:false});refreshFunnelRoutes(x.vacancyId);return calibrationResponse(ai,stored.value);}
export async function saveCalibrationReason(input:{vacancyId:number;reasonCode:string;note?:string}){const x=z.object({vacancyId:z.number().int(),reasonCode:z.enum(reasonCodes),note:z.string().trim().max(500).optional()}).parse(input);await storeFeedbackReason(getDb(),x);refreshFunnelRoutes(x.vacancyId);}
export async function savePreferences(form:FormData){ const id=Number(form.get("id")); const list=(k:string)=>String(form.get(k)||"").split(",").map(x=>x.trim()).filter(Boolean); await getDb().update(preferences).set({candidateContext:String(form.get("candidateContext")||"").trim(),hoursMin:Number(form.get("hoursMin")),hoursMax:Number(form.get("hoursMax")),salaryMin:form.get("salaryMin")?Number(form.get("salaryMin")):null,primaryCities:list("primaryCities"),secondaryCities:list("secondaryCities"),travelOrigin:String(form.get("travelOrigin")),maxTravelMinutes:Number(form.get("maxTravelMinutes")),roleFamilies:list("roleFamilies"),positiveIndicators:list("positiveIndicators"),negativeIndicators:list("negativeIndicators"),updatedAt:new Date()}).where(eq(preferences.id,id)); revalidatePath("/voorkeuren"); }
export async function toggleWatchedEmployer(form:FormData){const id=z.coerce.number().int().positive().parse(form.get("id"));const enabled=z.enum(["true","false"]).parse(form.get("enabled"))==="true";await getDb().update(watchedEmployers).set({enabled}).where(eq(watchedEmployers.id,id));revalidatePath("/voorkeuren");}
export async function addWatchedEmployer(form:FormData){const name=z.string().trim().min(1).max(200).parse(form.get("name"));await getDb().insert(watchedEmployers).values({name}).onConflictDoUpdate({target:watchedEmployers.name,set:{enabled:true}});revalidatePath("/voorkeuren");}
export async function toggleSource(form:FormData){ const id=Number(form.get("id")); await setSourceEnabled(getDb(),id,form.get("enabled")==="true"); revalidatePath("/bronnen"); }

export type TrackingState={status:"idle"|"success"|"error";message?:string;tracking?:TrackingData};
const vacancyIdSchema=z.coerce.number().int().positive();
function refreshTrackingRoutes(vacancyId:number){revalidatePath(`/vacatures/${vacancyId}`);revalidatePath("/");revalidatePath("/shortlist");}
async function upsertTracking(vacancyId:number,patch:Parameters<typeof trackingPatch>[0]){
  const values=trackingPatch(patch);const [stored]=await getDb().insert(vacancyTracking).values({vacancyId,...values}).onConflictDoUpdate({target:vacancyTracking.vacancyId,set:values}).returning({shortlistedAt:vacancyTracking.shortlistedAt,applicationStatus:vacancyTracking.applicationStatus,note:vacancyTracking.note});
  if(!stored)throw new Error("Tracking kon niet worden opgeslagen");return stored;
}
export async function saveShortlist(_state:TrackingState,form:FormData):Promise<TrackingState>{try{const vacancyId=vacancyIdSchema.parse(form.get("vacancyId"));const shortlisted=z.enum(["true","false"]).parse(form.get("shortlisted"))==="true";const tracking=await upsertTracking(vacancyId,{shortlistedAt:shortlisted?new Date():null});refreshTrackingRoutes(vacancyId);return{status:"success",message:shortlisted?"Toegevoegd aan shortlist.":"Verwijderd van shortlist.",tracking};}catch(error){console.error("Shortlist opslaan mislukt",error);return{status:"error",message:"Shortlist opslaan is niet gelukt. Probeer het opnieuw."};}}
export async function saveTrackingDetails(_state:TrackingState,form:FormData):Promise<TrackingState>{try{const x=z.object({vacancyId:vacancyIdSchema,applicationStatus:z.union([z.enum(applicationStatuses),z.literal("")]),note:z.string().trim().max(2000)}).parse(Object.fromEntries(form));const tracking=await upsertTracking(x.vacancyId,{applicationStatus:x.applicationStatus||null,note:x.note||null});refreshTrackingRoutes(x.vacancyId);return{status:"success",message:"Status en notitie opgeslagen.",tracking};}catch(error){console.error("Tracking opslaan mislukt",error);return{status:"error",message:"Status en notitie opslaan is niet gelukt. Probeer het opnieuw."};}}

export type WorkflowState={status:"idle"|"success"|"error";message?:string};
export async function startWorkflow(_state:WorkflowState,form:FormData):Promise<WorkflowState>{try{const action=workflowActionSchema.parse(form.get("workflow"));if("costly" in workflowActions[action]&&form.get("confirmed")!=="yes")return{status:"error",message:"Bevestig eerst dat deze herbeoordeling OpenAI-kosten kan veroorzaken."};await dispatchWorkflow(action);return{status:"success",message:`${workflowActions[action].label} is aangevraagd bij GitHub Actions.`};}catch(error){console.error("Workflow starten mislukt",error);return{status:"error",message:error instanceof Error?error.message:"Workflow starten is niet gelukt."};}}
