"use server"; import { cookies } from "next/headers"; import { redirect } from "next/navigation"; import { revalidatePath } from "next/cache"; import { z } from "zod"; import { eq } from "drizzle-orm"; import { createSession } from "@/lib/auth"; import { getDb } from "@/lib/db"; import { aiAssessments, feedback, preferences, sources, vacancyTracking } from "@/lib/db/schema"; import { eligibleFeedbackValues } from "@/lib/feedback-learning"; import { calibrationResponse } from "@/lib/calibration"; import { applicationStatuses, trackingPatch, type TrackingData } from "@/lib/vacancy-tracking";
export async function login(form:FormData){ if(!process.env.APP_PASSWORD||form.get("password")!==process.env.APP_PASSWORD) redirect("/login?error=1"); (await cookies()).set("vacature_session",await createSession(),{httpOnly:true,secure:process.env.NODE_ENV==="production",sameSite:"lax",path:"/",maxAge:2592000}); redirect("/"); }
export type FeedbackState={status:"idle"|"success"|"error";message?:string;value?:"interesting"|"maybe"|"not_suitable"};
async function persistFeedback(input:{vacancyId:number;value:"interesting"|"maybe"|"not_suitable";reasonCode?:string|null;note?:string|null},aiVerdict:"interesting"|"maybe"|"not_suitable"|null){const values=eligibleFeedbackValues({...input,reasonCode:input.reasonCode||null,note:input.note||null},aiVerdict);const [stored]=await getDb().insert(feedback).values(values).onConflictDoUpdate({target:feedback.vacancyId,set:{...values,updatedAt:new Date()}}).returning({value:feedback.value});if(!stored)throw new Error("Feedback kon niet worden opgeslagen");return stored.value;}
export async function saveFeedback(_previousState:FeedbackState,form:FormData):Promise<FeedbackState>{try{const x=z.object({vacancyId:z.coerce.number().int(),value:z.enum(["interesting","maybe","not_suitable"]),reasonCode:z.string().max(100).optional(),note:z.string().max(2000).optional()}).parse(Object.fromEntries(form));const db=getDb();const [ai]=await db.select({verdict:aiAssessments.verdict}).from(aiAssessments).where(eq(aiAssessments.vacancyId,x.vacancyId)).limit(1);const storedValue=await persistFeedback(x,ai?.verdict??null);revalidatePath(`/vacatures/${x.vacancyId}`);return{status:"success",message:"Opgeslagen",value:storedValue};}catch(error){console.error("Feedback opslaan mislukt",error);return{status:"error",message:"Opslaan is niet gelukt. Probeer het opnieuw."};}}
const choiceSchema=z.object({vacancyId:z.number().int(),value:z.enum(["interesting","maybe","not_suitable"])});
export async function submitCalibrationChoice(input:z.infer<typeof choiceSchema>){const x=choiceSchema.parse(input);const db=getDb();const [ai]=await db.select({verdict:aiAssessments.verdict,score:aiAssessments.score,summary:aiAssessments.summary,positives:aiAssessments.positives,concerns:aiAssessments.concerns}).from(aiAssessments).where(eq(aiAssessments.vacancyId,x.vacancyId)).limit(1);if(!ai)throw new Error("AI-beoordeling niet gevonden");const storedValue=await persistFeedback({vacancyId:x.vacancyId,value:x.value},ai.verdict);revalidatePath("/");return calibrationResponse(ai,storedValue);}
export async function saveCalibrationReason(input:{vacancyId:number;reasonCode:string;note?:string}){const x=z.object({vacancyId:z.number().int(),reasonCode:z.enum(["role","seniority","location","hours","salary","employer","other"]),note:z.string().trim().max(500).optional()}).parse(input);if(x.reasonCode==="other"&&!x.note)throw new Error("Licht 'Iets anders' kort toe.");await getDb().update(feedback).set({reasonCode:x.reasonCode,note:x.note||null,learningEligible:true,updatedAt:new Date()}).where(eq(feedback.vacancyId,x.vacancyId));revalidatePath("/");}
export async function savePreferences(form:FormData){ const id=Number(form.get("id")); const list=(k:string)=>String(form.get(k)||"").split(",").map(x=>x.trim()).filter(Boolean); await getDb().update(preferences).set({hoursMin:Number(form.get("hoursMin")),hoursMax:Number(form.get("hoursMax")),salaryMin:form.get("salaryMin")?Number(form.get("salaryMin")):null,primaryCities:list("primaryCities"),secondaryCities:list("secondaryCities"),travelOrigin:String(form.get("travelOrigin")),maxTravelMinutes:Number(form.get("maxTravelMinutes")),roleFamilies:list("roleFamilies"),positiveIndicators:list("positiveIndicators"),negativeIndicators:list("negativeIndicators"),updatedAt:new Date()}).where(eq(preferences.id,id)); revalidatePath("/voorkeuren"); }
export async function toggleSource(form:FormData){ const id=Number(form.get("id")); await getDb().update(sources).set({enabled:form.get("enabled")==="true"}).where(eq(sources.id,id)); revalidatePath("/bronnen"); }

export type TrackingState={status:"idle"|"success"|"error";message?:string;tracking?:TrackingData};
const vacancyIdSchema=z.coerce.number().int().positive();
function refreshTrackingRoutes(vacancyId:number){revalidatePath(`/vacatures/${vacancyId}`);revalidatePath("/");revalidatePath("/shortlist");}
async function upsertTracking(vacancyId:number,patch:Parameters<typeof trackingPatch>[0]){
  const values=trackingPatch(patch);const [stored]=await getDb().insert(vacancyTracking).values({vacancyId,...values}).onConflictDoUpdate({target:vacancyTracking.vacancyId,set:values}).returning({shortlistedAt:vacancyTracking.shortlistedAt,applicationStatus:vacancyTracking.applicationStatus,note:vacancyTracking.note});
  if(!stored)throw new Error("Tracking kon niet worden opgeslagen");return stored;
}
export async function saveShortlist(_state:TrackingState,form:FormData):Promise<TrackingState>{try{const vacancyId=vacancyIdSchema.parse(form.get("vacancyId"));const shortlisted=z.enum(["true","false"]).parse(form.get("shortlisted"))==="true";const tracking=await upsertTracking(vacancyId,{shortlistedAt:shortlisted?new Date():null});refreshTrackingRoutes(vacancyId);return{status:"success",message:shortlisted?"Toegevoegd aan shortlist.":"Verwijderd van shortlist.",tracking};}catch(error){console.error("Shortlist opslaan mislukt",error);return{status:"error",message:"Shortlist opslaan is niet gelukt. Probeer het opnieuw."};}}
export async function saveTrackingDetails(_state:TrackingState,form:FormData):Promise<TrackingState>{try{const x=z.object({vacancyId:vacancyIdSchema,applicationStatus:z.union([z.enum(applicationStatuses),z.literal("")]),note:z.string().trim().max(2000)}).parse(Object.fromEntries(form));const tracking=await upsertTracking(x.vacancyId,{applicationStatus:x.applicationStatus||null,note:x.note||null});refreshTrackingRoutes(x.vacancyId);return{status:"success",message:"Status en notitie opgeslagen.",tracking};}catch(error){console.error("Tracking opslaan mislukt",error);return{status:"error",message:"Status en notitie opslaan is niet gelukt. Probeer het opnieuw."};}}
