import Link from "next/link";
import { and, count, desc, eq, gte, isNull, sql } from "drizzle-orm";
import { getDb } from "@/lib/db";
import { aiAssessments, feedback, sourceRuns, sources, vacancies } from "@/lib/db/schema";
import { verdictLabels } from "@/lib/calibration";
import { categoryLabel, parseIngestionWarning, sourceHealth, warningCounts } from "@/lib/ingestion/shared/ingestion-warnings";
export const dynamic = "force-dynamic";
function Notices({values}:{values:string[]}){if(!values.length)return null;const counts=warningCounts(values);return <details className="notices"><summary>{counts.critical+counts.warning} aandachtspunt(en)</summary>{values.map((value,i)=>{const item=parseIngestionWarning(value);return <div className={`notice notice-${item.severity}`} key={i}><b>{categoryLabel(item.category)}</b><br/>{item.message}</div>})}</details>}
const hours=(x:{hoursMin:number|null;hoursMax:number|null})=>x.hoursMin?`${x.hoursMin}${x.hoursMax&&x.hoursMax!==x.hoursMin?`–${x.hoursMax}`:""} uur`:"Uren onbekend";
export default async function Home(){const db=getDb();const [[recent],[interesting],[reviewed],[waiting],cards,runs,activeRuns]=await Promise.all([
 db.select({n:count()}).from(vacancies).where(and(eq(vacancies.active,true),gte(vacancies.firstSeenAt,sql`now() - interval '7 days'`))),
 db.select({n:count()}).from(vacancies).innerJoin(aiAssessments,eq(aiAssessments.vacancyId,vacancies.id)).where(and(eq(vacancies.active,true),eq(aiAssessments.verdict,"interesting"))),
 db.select({n:count()}).from(feedback),
 db.select({n:count()}).from(vacancies).innerJoin(aiAssessments,eq(aiAssessments.vacancyId,vacancies.id)).leftJoin(feedback,eq(feedback.vacancyId,vacancies.id)).where(and(eq(vacancies.active,true),isNull(feedback.id))),
 db.select({id:vacancies.id,title:vacancies.title,employer:vacancies.employer,location:vacancies.location,hoursMin:vacancies.hoursMin,hoursMax:vacancies.hoursMax,salaryMin:vacancies.salaryMin,salaryMax:vacancies.salaryMax,salaryOriginal:vacancies.salaryOriginal,deadline:vacancies.deadline,score:aiAssessments.score,verdict:aiAssessments.verdict}).from(vacancies).innerJoin(aiAssessments,eq(aiAssessments.vacancyId,vacancies.id)).where(and(eq(vacancies.active,true),eq(aiAssessments.verdict,"interesting"))).orderBy(desc(vacancies.firstSeenAt),desc(aiAssessments.score)).limit(5),
 db.select({name:sources.name,status:sourceRuns.status,finished:sourceRuns.finishedAt,count:sourceRuns.resultCount,warnings:sourceRuns.warnings}).from(sourceRuns).innerJoin(sources,eq(sourceRuns.sourceId,sources.id)).orderBy(desc(sourceRuns.startedAt)).limit(5),
 db.select({id:sources.id,status:sourceRuns.status}).from(sources).leftJoin(sourceRuns,eq(sources.id,sourceRuns.sourceId)).where(eq(sources.enabled,true)).orderBy(desc(sourceRuns.startedAt))]);
 const latest=[...new Map(activeRuns.map(r=>[r.id,r])).values()];return <><section className="hero"><div><p className="eyebrow">Jouw vacatureselectie</p><h1>Maak ruimte voor werk dat bij je past.</h1><p className="lead">Er wachten <b>{waiting.n}</b> door AI beoordeelde vacatures op jouw eigen oordeel.</p></div><Link className="button button-large" href="/kalibreren">Beoordeel 5 vacatures</Link></section><section className="metrics" aria-label="Samenvatting"><div><span>Nieuwe vacatures deze week</span><strong>{recent.n}</strong></div><div><span>AI: interessant</span><strong>{interesting.n}</strong></div><div><span>Door mij beoordeeld</span><strong>{reviewed.n}</strong></div><div><span>Nog te beoordelen</span><strong>{waiting.n}</strong></div></section><section className="section-head"><div><p className="eyebrow">Om te bekijken</p><h2>Nieuwe interessante vacatures</h2></div><Link href="/vacatures?ai=interesting&sort=ai-score">Bekijk alle vacatures →</Link></section><div className="vacancy-cards">{cards.map(x=><Link className="vacancy-card" href={`/vacatures/${x.id}`} key={x.id}><div><h3>{x.title}</h3><p>{x.employer}</p></div><span className="ai-badge">AI {x.score} · {verdictLabels[x.verdict]}</span><dl><div><dt>Locatie</dt><dd>{x.location||"Niet vermeld"}</dd></div><div><dt>Uren</dt><dd>{hours(x)}</dd></div><div><dt>Salaris</dt><dd>{x.salaryMin?`€ ${x.salaryMin.toLocaleString("nl-NL")}${x.salaryMax?`–${x.salaryMax.toLocaleString("nl-NL")}`:""}`:x.salaryOriginal||"Niet vermeld"}</dd></div><div><dt>Deadline</dt><dd>{x.deadline?.toLocaleDateString("nl-NL")||"Niet vermeld"}</dd></div></dl></Link>)}{!cards.length&&<p className="muted">Nog geen interessante vacatures gevonden.</p>}</div><section className="operations"><div className="section-head"><div><p className="eyebrow">Systeeminformatie</p><h2>Bronnen en recente runs</h2></div><span className="muted">Brongezondheid: {sourceHealth(latest.map(x=>x.status))}</span></div>{runs.map((run,i)=><div className="run" key={i}><b>{run.name}</b><span>{run.status} · {run.count} resultaten · {run.finished?.toLocaleString("nl-NL")||"bezig"}</span><Notices values={run.warnings}/></div>)}</section></>}
