"use client";
import Link from "next/link";
import { useState, useTransition } from "react";
import { saveCalibrationReason, submitCalibrationChoice } from "@/app/actions";
import { calibrationSummary, compactExcerpt, verdictLabels, type BlindVacancy, type ReasonCode, type Verdict } from "@/lib/calibration";

const reasons: [ReasonCode,string][]=[["role","Functie / inhoud"],["seniority","Niveau / verantwoordelijkheid"],["location","Locatie / reistijd"],["hours","Uren"],["salary","Salaris"],["employer","Werkgever / sector"],["other","Iets anders"]];
const formatHours=(v:BlindVacancy)=>v.hoursMin?`${v.hoursMin}${v.hoursMax&&v.hoursMax!==v.hoursMin?`–${v.hoursMax}`:""} uur`:v.hoursOriginal||"Niet vermeld";
const formatSalary=(v:BlindVacancy)=>v.salaryMin?`€ ${v.salaryMin.toLocaleString("nl-NL")}${v.salaryMax?`–${v.salaryMax.toLocaleString("nl-NL")}`:""}`:v.salaryOriginal||"Niet vermeld";
type Reveal={verdict:Verdict;score:number;summary:string;agreed:boolean};
export default function CalibrationFlow({vacancies}:{vacancies:BlindVacancy[]}){
 const [index,setIndex]=useState(0),[results,setResults]=useState<{userVerdict:Verdict;aiVerdict:Verdict}[]>([]),[choice,setChoice]=useState<Verdict>(),[reveal,setReveal]=useState<Reveal>(),[reason,setReason]=useState<ReasonCode>(),[note,setNote]=useState(""),[error,setError]=useState(""); const [pending,start]=useTransition();
 const vacancy=vacancies[index];
 const choose=(value:Verdict)=>start(async()=>{try{setError("");const result=await submitCalibrationChoice({vacancyId:vacancy.id,value});setChoice(value);setReveal(result);}catch(e){setError(e instanceof Error?e.message:"Opslaan mislukt");}});
 const next=()=>{if(choice&&reveal)setResults(x=>[...x,{userVerdict:choice,aiVerdict:reveal.verdict}]);setIndex(x=>x+1);setChoice(undefined);setReveal(undefined);setReason(undefined);setNote("");};
 const submitReason=()=>start(async()=>{if(!reason)return setError("Kies eerst een reden.");try{setError("");await saveCalibrationReason({vacancyId:vacancy.id,reasonCode:reason,note});next();}catch(e){setError(e instanceof Error?e.message:"Opslaan mislukt");}});
 if(!vacancies.length)return <section className="empty-state"><p className="eyebrow">Kalibreren</p><h1>Je bent helemaal bij</h1><p>Er zijn nu geen actieve, door AI beoordeelde vacatures zonder jouw oordeel.</p><Link className="button" href="/vacatures">Naar vacatures</Link></section>;
 if(index>=vacancies.length){const summary=calibrationSummary(results);return <section className="batch-summary"><p className="eyebrow">Batch afgerond</p><h1>{summary.total} vacatures beoordeeld</h1><div className="summary-numbers"><div><strong>{summary.agreed}</strong><span>eens met AI</span></div><div><strong>{summary.differed}</strong><span>anders beoordeeld</span></div><div><strong>{summary.agreementPercentage}%</strong><span>overeenstemming</span></div></div><h2>Jouw oordelen</h2><p>Interessant <b>{summary.breakdown.interesting}</b> · Misschien <b>{summary.breakdown.maybe}</b> · Niet passend <b>{summary.breakdown.not_suitable}</b></p><div className="actions"><a className="button" href="/kalibreren">Nog 5 beoordelen</a><Link className="button secondary" href="/vacatures">Naar vacatures</Link></div></section>}
 return <div className="calibration"><header className="calibration-head"><div><p className="eyebrow">Blind beoordelen</p><h1>{vacancy.title}</h1><p className="lead">{vacancy.employer}</p></div><b>{index+1} van {vacancies.length}</b></header><div className="progress"><span style={{width:`${(index+1)/vacancies.length*100}%`}}/></div><article className="vacancy-review"><dl className="metadata"><div><dt>Locatie</dt><dd>{vacancy.location||"Niet vermeld"}</dd></div><div><dt>Uren</dt><dd>{formatHours(vacancy)}</dd></div><div><dt>Salaris</dt><dd>{formatSalary(vacancy)}</dd></div><div><dt>Deadline</dt><dd>{vacancy.deadline?new Date(vacancy.deadline).toLocaleDateString("nl-NL"):"Niet vermeld"}</dd></div></dl><p className="excerpt">{compactExcerpt(vacancy)}</p><Link href={`/vacatures/${vacancy.id}`}>Volledige vacature bekijken →</Link></article>
 {!reveal?<section className="decision"><h2>Wat vind jij van deze vacature?</h2><div className="choice-grid">{(Object.keys(verdictLabels) as Verdict[]).map(value=><button disabled={pending} className="choice" key={value} onClick={()=>choose(value)}>{verdictLabels[value]}</button>)}</div></section>:<section className={`reveal ${reveal.agreed?"agreement":"disagreement"}`}>{reveal.agreed?<><h2>Eens — AI beoordeelde deze ook als {verdictLabels[reveal.verdict]} ({reveal.score}).</h2><button onClick={next}>Volgende vacature</button></>:<><p className="eyebrow">Verschil in beoordeling</p><h2>Jij: {verdictLabels[choice!]} · AI: {verdictLabels[reveal.verdict]} ({reveal.score})</h2><p>{reveal.summary}</p><hr/><h3>Waarom beoordeel jij deze anders?</h3><div className="reason-grid">{reasons.map(([value,label])=><label key={value}><input type="radio" name="reason" checked={reason===value} onChange={()=>setReason(value)}/><span>{label}</span></label>)}</div><textarea value={note} onChange={e=>setNote(e.target.value)} maxLength={500} placeholder={reason==="other"?"Korte toelichting (verplicht)":"Eventuele korte notitie"}/><button disabled={pending} onClick={submitReason}>Reden opslaan en verder</button></>}</section>}{error&&<p className="error">{error}</p>}</div>;
}
